export const ORDER_COURSES = [
  "All Courses",
  "NEET PG",
  "NEET SS",
  "FMGE",
  "MBBS Curriculum",
  "PG Residency",
];

export const ORDER_STATUSES = [
  "All Status",
  "Success",
  "Pending",
  "Failed",
  "Cancelled",
];

export const DUMMY_ORDERS = [
  {
    orderID: 50001,
    studentID: 1001,
    studentName: "Arun Kumar",
    mobileNo: "9876543210",
    email: "arun.kumar@example.com",
    course: "NEET PG",
    planName: "NEET PG Premium",
    amount: 12999,
    paymentMethod: "Online",
    orderDate: "2026-09-02",
    status: "Success",
  },
  {
    orderID: 50002,
    studentID: 1002,
    studentName: "Priya Sharma",
    mobileNo: "9876543211",
    email: "priya.sharma@example.com",
    course: "NEET SS",
    planName: "NEET SS Complete",
    amount: 8999,
    paymentMethod: "UPI",
    orderDate: "2026-09-04",
    status: "Success",
  },
  {
    orderID: 50003,
    studentID: 1003,
    studentName: "Rahul Verma",
    mobileNo: "9876543212",
    email: "rahul.verma@example.com",
    course: "FMGE",
    planName: "FMGE Premium",
    amount: 6999,
    paymentMethod: "Card",
    orderDate: "2026-09-06",
    status: "Pending",
  },
  {
    orderID: 50004,
    studentID: 1004,
    studentName: "Sneha Reddy",
    mobileNo: "9876543213",
    email: "sneha.reddy@example.com",
    course: "MBBS Curriculum",
    planName: "MBBS Complete",
    amount: 4999,
    paymentMethod: "UPI",
    orderDate: "2026-09-08",
    status: "Success",
  },
  {
    orderID: 50005,
    studentID: 1005,
    studentName: "Vikram Singh",
    mobileNo: "9876543214",
    email: "vikram.singh@example.com",
    course: "NEET PG",
    planName: "NEET PG Standard",
    amount: 7999,
    paymentMethod: "Online",
    orderDate: "2026-09-10",
    status: "Failed",
  },
  {
    orderID: 50006,
    studentID: 1006,
    studentName: "Anjali Nair",
    mobileNo: "9876543215",
    email: "anjali.nair@example.com",
    course: "PG Residency",
    planName: "PG Residency Premium",
    amount: 10999,
    paymentMethod: "Card",
    orderDate: "2026-09-12",
    status: "Success",
  },
  {
    orderID: 50007,
    studentID: 1007,
    studentName: "Karthik Rao",
    mobileNo: "9876543216",
    email: "karthik.rao@example.com",
    course: "NEET PG",
    planName: "NEET PG Premium",
    amount: 12999,
    paymentMethod: "UPI",
    orderDate: "2026-09-15",
    status: "Cancelled",
  },
  {
    orderID: 50008,
    studentID: 1008,
    studentName: "Meera Joseph",
    mobileNo: "9876543217",
    email: "meera.joseph@example.com",
    course: "FMGE",
    planName: "FMGE Standard",
    amount: 5999,
    paymentMethod: "Online",
    orderDate: "2026-09-18",
    status: "Success",
  },
] as const;